APCA_API_KEY_ID = 'Your Alpaca key ID'
APCA_API_SECRET_KEY = 'Your Alpaca Secret Key'
ALCHEMY_URL = 'Your Alchemy HTTP URL for Polygon'
BASE_ACCOUNT = 'Your Web3 Wallet addres'
PRIVATE_KEY = 'Prive key for the wallet address mentioned above'
